//I followed a tutorial and this is how the dude organized the names of the scenes.
//TBH i have no idea how this works but it works

export const SCENE_KEYS = Object.freeze({
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    MAIN_MENU_SCENE: 'MAIN_MENU_SCENE',
    GAME_START_SCENE: 'GAME_START_SCENE',
    CREDITS_SCENE: 'CREDITS_SCENE',
    LEVELONE_SCENE: 'LEVELONE_SCENE',
    LEVELTWO_SCENE: 'LEVELTWO_SCENE',
    LEVELTHREE_SCENE: 'LEVELTHREE_SCENE',
    LEVELFOUR_SCENE: 'LEVELFOUR_SCENE',
    LEVELFIVE_SCENE: 'LEVELFIVE_SCENE',
    LEVELSIX_SCENE: 'LEVELSIX_SCENE',
    LEVELSEVEN_SCENE: 'LEVELSEVEN_SCENE',
    LEVELEIGHT_SCENE: 'LEVELEIGHT_SCENE',
    LEVELFINAL_SCENE: 'LEVELFINAL_SCENE',
})